# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: npmAuthenticate@0
  displayName: 'npm Authenticate .npmrc'
  inputs:
    workingFile: .npmrc

# - script: |
#     npm install vsts-npm-auth --registry https://registry.npmjs.com
#     npm run npm-auth
#   displayName: 'npm auth'

- script: |
    npm install vsts-npm-auth
    vsts-npm-auth -config .npmrc
  displayName: 'npm auth'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
