# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-16.04'

# pool:
#   name: Azure Pipelines
#   demands: npm

steps:
- task: npmAuthenticate@0
  displayName: 'npm Authenticate .npmrc'
  inputs:
    workingFile: .npmrc

- script: |
    npm run npm-auth
  displayName: 'npm auth'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

# steps:
# - task: npmAuthenticate@0
#   displayName: 'npm Authenticate .npmrc'
#   inputs:
#     workingFile: .npmrc

# - task: Npm@1
#   displayName: 'npm install'
#   inputs:
#     verbose: false

# - script: |
#     npm run build:parser
#   displayName: 'build'

# - script: |
#     npm run pipelineTest
#   displayName: 'run tests'
